import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'sv';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    'header.search.placeholder': 'Search students, schools, reports...',
    'header.breadcrumb.dashboard': 'Dashboard',
    'header.breadcrumb.students': 'Student Management > Student Registry',
    'header.breadcrumb.students.placements': 'Student Management > Placements & Transfers',
    'header.breadcrumb.students.conflicts': 'Student Management > Conflict Resolution',
    'header.breadcrumb.students.bulk': 'Student Management > Bulk Operations',
    'header.breadcrumb.financial': 'Financial Management > IKE Calculations',
    'header.breadcrumb.financial.pricelists': 'Financial Management > Price Lists',
    'header.breadcrumb.reports': 'Reports & Analysis > Standard Reports',
    'header.breadcrumb.reports.contributions': 'Reports & Analysis > Contribution Reports',
    'header.breadcrumb.reports.statistics': 'Reports & Analysis > Statistics',
    'header.breadcrumb.reports.follow-up': 'Reports & Analysis > Follow-up Reports',
    'header.breadcrumb.integration': 'Integration & Import',
    'header.breadcrumb.settings': 'Settings',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to IKE 2.0',
    'dashboard.date': 'Skåne Regional Platform',
    'dashboard.export': 'Export Data',
    'dashboard.generate': 'Generate Report',
    'dashboard.total.students': 'Total Students',
    'dashboard.active.calculations': 'Active Calculations',
    'dashboard.pending.conflicts': 'Pending Conflicts',
    'dashboard.monthly.amount': 'Monthly Amount',
    'dashboard.from.last.month': 'from last month',
    'dashboard.ongoing.processing': 'Ongoing processing',
    'dashboard.requires.attention': 'Requires attention',
    'dashboard.for.november': 'SEK for November 2024',
    'dashboard.calculation.status': 'Current Calculation Status',
    'dashboard.monthly.calculation': 'Monthly IKE calculation for November 2024',
    'dashboard.data.validation': 'Data validation',
    'dashboard.preliminary.calculation': 'Preliminary calculation',
    'dashboard.final.calculation': 'Final calculation',
    'dashboard.completed': 'Completed',
    'dashboard.ongoing': 'Ongoing',
    'dashboard.pending': 'Pending',
    'dashboard.next.run': 'Next run:',
    'dashboard.quick.actions': 'Quick Actions',
    'dashboard.common.tasks': 'Common tasks and functions',
    'dashboard.new.student': 'New Student',
    'dashboard.new.calculation': 'New Calculation',
    'dashboard.resolve.conflicts': 'Resolve Conflicts',
    'dashboard.recent.activity': 'Recent Activity',
    'dashboard.system.events': 'Overview of system events and user activity',
    'dashboard.student.registered': 'New student registered',
    'dashboard.conflict.resolved': 'Conflict resolved',
    'dashboard.calculation.started': 'Calculation started',
    'dashboard.data.imported': 'Data imported',
    'dashboard.done': 'Done',
    'dashboard.resolved': 'Resolved',
    
    // Students
    'students.title': 'Student Registry',
    'students.subtitle': 'Manage student registration and placements',
    'students.export': 'Export',
    'students.new.student': 'New Student',
    'students.total.students': 'Total Students',
    'students.intercommunal': 'Intercommunal',
    'students.pending.transfers': 'Pending Transfers',
    'students.new.this.month': 'New this Month',
    'students.search.filter': 'Search and Filter',
    'students.search.placeholder': 'Search by name or personal number...',
    'students.all.statuses': 'All statuses',
    'students.all.municipalities': 'All municipalities',
    'students.active': 'Active',
    'students.conflict': 'Conflict',
    'students.pending': 'Pending',
    'students.unknown': 'Unknown',
    'students.student.list': 'Students',
    'students.detailed.list': 'Detailed list of all registered students',
    'students.name': 'Name',
    'students.personal.number': 'Personal Number',
    'students.municipality': 'Municipality',
    'students.school': 'School',
    'students.program': 'Program',
    'students.class': 'Class',
    'students.status': 'Status',
    'students.amount': 'Amount (SEK)',
    'students.actions': 'Actions',
    'students.view.details': 'View details',
    'students.edit': 'Edit',
    'students.transfer': 'Transfer',

    // Student Placements
    'placements.title': 'Placements & Transfers',
    'placements.subtitle': 'Manage student transfers between municipalities and schools',
    'placements.new.transfer': 'New Transfer',
    'placements.pending.transfers': 'Pending Transfers',
    'placements.requires.approval': 'Requires approval',
    'placements.approved.this.month': 'Approved this Month',
    'placements.from.last.month': 'from last month',
    'placements.completed.transfers': 'Completed transfers',
    'placements.since.term.start': 'Since term start',
    'placements.current.requests': 'Current Transfer Requests',
    'placements.recent.transfers': 'Recent and ongoing student transfers',
    'placements.from': 'From:',
    'placements.to': 'To:',
    'placements.program': 'Program:',
    'placements.reason': 'Reason:',
    'placements.pending': 'Pending',
    'placements.approved': 'Approved',
    'placements.completed': 'Completed',
    'placements.unknown': 'Unknown',
    'placements.approve': 'Approve',
    'placements.reject': 'Reject',
    'placements.execute': 'Execute',
    'placements.view.details': 'View details',
    'placements.transfer.process': 'Transfer Process',
    'placements.process.description': 'Standard process for student transfers between municipalities',
    'placements.step.application': 'Application received',
    'placements.step.application.desc': 'Student or guardian submits application',
    'placements.step.review': 'Review',
    'placements.step.review.desc': 'Both sending and receiving school review the application',
    'placements.step.approval': 'Approval',
    'placements.step.approval.desc': 'Decision made by responsible administrator',
    'placements.step.execution': 'Execution',
    'placements.step.execution.desc': 'System updates student registry and calculates new contributions',

    // Student Conflicts
    'conflicts.title': 'Conflict Resolution',
    'conflicts.subtitle': 'Identify and resolve conflicts in the student registry',
    'conflicts.run.analysis': 'Run Conflict Analysis',
    'conflicts.active.conflicts': 'Active Conflicts',
    'conflicts.requires.attention': 'Requires attention',
    'conflicts.under.investigation': 'Under Investigation',
    'conflicts.ongoing.process': 'Ongoing process',
    'conflicts.resolved.this.month': 'Resolved this Month',
    'conflicts.resolution.rate': '94% resolution rate',
    'conflicts.average.resolution.time': 'Average Resolution Time',
    'conflicts.days': 'days',
    'conflicts.active.conflicts.list': 'Active Conflicts',
    'conflicts.requires.immediate.attention': 'Conflicts that require immediate attention and action',
    'conflicts.detected': 'Detected:',
    'conflicts.responsible': 'Responsible:',
    'conflicts.school': 'School',
    'conflicts.choose.placement': 'Choose Placement',
    'conflicts.edit': 'Edit',
    'conflicts.mark.resolved': 'Mark Resolved',
    'conflicts.comments': 'Comments',
    'conflicts.resolution.process': 'Conflict Resolution Process',
    'conflicts.standard.process': 'Standard process for resolving conflicts in the student registry',
    'conflicts.step.automatic.detection': 'Automatic Detection',
    'conflicts.step.automatic.detection.desc': 'System identifies potential conflicts during data registration',
    'conflicts.step.prioritization': 'Prioritization',
    'conflicts.step.prioritization.desc': 'Conflicts are prioritized based on type and impact',
    'conflicts.step.investigation': 'Investigation',
    'conflicts.step.investigation.desc': 'Responsible administrator contacts affected schools',
    'conflicts.step.resolution': 'Resolution',
    'conflicts.step.resolution.desc': 'Correct placement is determined and system is updated',
    'conflicts.double.registration': 'Double Registration',
    'conflicts.wrong.municipality': 'Wrong Municipality',
    'conflicts.date.conflict': 'Date Conflict',
    'conflicts.pending': 'Pending',
    'conflicts.investigating': 'Investigating',
    'conflicts.resolved': 'Resolved',
    'conflicts.unknown': 'Unknown',
    'conflicts.priority.high': 'High',
    'conflicts.priority.medium': 'Medium',
    'conflicts.priority.low': 'Low',

    // Bulk Operations
    'bulk.title': 'Bulk Operations',
    'bulk.subtitle': 'Efficiently manage large amounts of student data',
    'bulk.templates': 'Templates',
    'bulk.new.operation': 'New Operation',
    'bulk.import.student.data': 'Import Student Data',
    'bulk.import.description': 'Import data from SS12000 or Excel files',
    'bulk.start.import': 'Start Import',
    'bulk.year.advancement': 'Year Advancement',
    'bulk.advancement.description': 'Advance students to next grade level',
    'bulk.start.advancement': 'Start Advancement',
    'bulk.export.data': 'Export Data',
    'bulk.export.description': 'Export student data for reports or backup',
    'bulk.start.export': 'Start Export',
    'bulk.recent.operations': 'Recent and Ongoing Operations',
    'bulk.operations.description': 'Status of bulk operations and data processing',
    'bulk.started.by': 'Started by:',
    'bulk.progress': 'Progress',
    'bulk.total': 'Total:',
    'bulk.processed': 'Processed:',
    'bulk.successful': 'Successful:',
    'bulk.failed': 'Failed:',
    'bulk.start': 'Start:',
    'bulk.end': 'End:',
    'bulk.not.started': 'Not started',
    'bulk.cancel': 'Cancel',
    'bulk.show.errors': 'Show Errors',
    'bulk.details': 'Details',
    'bulk.completed': 'Completed',
    'bulk.running': 'Running',
    'bulk.pending': 'Pending',
    'bulk.failed.status': 'Failed',
    'bulk.unknown': 'Unknown',
    'bulk.import.guidelines': 'Import Guidelines',
    'bulk.guidelines.description': 'Important guidelines for data import and bulk operations',
    'bulk.ss12000.standard': 'SS12000 Standard',
    'bulk.ss12000.description': 'Use SS12000 format to ensure compatibility and data quality',
    'bulk.validation.before.import': 'Validation before Import',
    'bulk.validation.description': 'Always verify data in test environment before importing to production system',
    'bulk.backup.before.operations': 'Backup before Bulk Operations',
    'bulk.backup.description': 'Ensure complete backup exists before performing large changes',
    'bulk.communication': 'Communication',
    'bulk.communication.description': 'Inform affected parties about planned bulk operations in good time',

    // Financial
    'financial.title': 'IKE Calculations',
    'financial.subtitle': 'Manage monthly calculations for intercommunal compensation',
    'financial.export.results': 'Export Results',
    'financial.new.calculation': 'New Calculation',
    'financial.total.monthly.cost': 'Total Monthly Cost',
    'financial.from.last.month': 'from last month',
    'financial.average.per.student': 'Average per Student',
    'financial.monthly.average': 'Monthly average',
    'financial.active.students': 'Active Students',
    'financial.included.in.calculation': 'Included in calculation',
    'financial.next.calculation': 'Next Calculation',
    'financial.scheduled.run': 'Scheduled run',
    'financial.current.calculation.status': 'Current Calculation Status',
    'financial.detailed.status': 'Detailed status for ongoing monthly calculation',
    'financial.data.validation': 'Data validation',
    'financial.price.calculation': 'Price calculation',
    'financial.export.distribution': 'Export & Distribution',
    'financial.completed': 'Completed',
    'financial.ongoing': 'Ongoing',
    'financial.pending': 'Pending',
    'financial.validated.posts': 'Validated {count} student posts',
    'financial.processed.students': 'Processed {current} of {total} students',
    'financial.waiting.completion': 'Waiting for calculation completion',
    'financial.started': 'Started:',
    'financial.estimated.completion': 'Estimated completion:',
    'financial.show.details': 'Show Details',
    'financial.calculation.history': 'Calculation History',
    'financial.previous.calculations': 'Overview of previous monthly calculations',
    'financial.completed.short': 'Completed:',
    'financial.total.amount': 'Total amount:',
    'financial.number.of.students': 'Number of students:',
    'financial.average.per.student.short': 'Average/student:',
    'financial.details': 'Details',
    'financial.export': 'Export',
    'financial.municipality.breakdown': 'Municipality Breakdown',
    'financial.cost.distribution': 'Cost distribution per municipality for current month',
    'financial.students': 'students',
    'financial.sek.per.student': 'SEK/student',
    'financial.failed': 'Failed',
    'financial.unknown': 'Unknown',

    // Price Lists
    'pricelists.title': 'Price Lists',
    'pricelists.subtitle': 'Manage prices for programs and specializations',
    'pricelists.price.history': 'Price History',
    'pricelists.new.pricelist': 'New Price List',
    'pricelists.active.pricelists': 'Active Price Lists',
    'pricelists.over.municipalities': 'Over 33 municipalities',
    'pricelists.average.price': 'Average Price',
    'pricelists.sek.per.student.year': 'SEK per student/year',
    'pricelists.updates.this.year': 'Updates this Year',
    'pricelists.price.changes.2024': 'Price changes 2024',
    'pricelists.price.increase': 'Price Increase',
    'pricelists.compared.to.2023': 'Compared to 2023',
    'pricelists.pricelists.per.municipality': 'Price Lists per Municipality',
    'pricelists.overview.active.planned': 'Overview of active and planned price lists',
    'pricelists.search.pricelists': 'Search price lists...',
    'pricelists.municipality': 'Municipality',
    'pricelists.type': 'Type',
    'pricelists.valid.from': 'Valid from',
    'pricelists.valid.to': 'Valid to',
    'pricelists.programs': 'Programs',
    'pricelists.average.price.short': 'Average Price',
    'pricelists.status': 'Status',
    'pricelists.actions': 'Actions',
    'pricelists.active': 'Active',
    'pricelists.draft': 'Draft',
    'pricelists.expired': 'Expired',
    'pricelists.unknown': 'Unknown',
    'pricelists.program.prices.malmo': 'Program Prices - Malmö Municipality',
    'pricelists.detailed.prices': 'Detailed prices for different programs and specializations',
    'pricelists.program.code': 'Program Code',
    'pricelists.program.name': 'Program Name',
    'pricelists.specialization': 'Specialization',
    'pricelists.normal.price': 'Normal Price',
    'pricelists.internal.price': 'Internal Price',
    'pricelists.price.trends': 'Price Trends',
    'pricelists.development.average.prices': 'Development of average prices over time',
    'pricelists.interactive.trend.chart': 'Interactive trend chart would be shown here',
    'pricelists.visualization.price.changes': '(Visualization of price changes over time)',
    'pricelists.from.previous.year': 'from {year}',

    // Reports
    'reports.title': 'Standard Reports',
    'reports.subtitle': 'Generate and manage common system reports',
    'reports.new.report': 'New Report',
    'reports.search.placeholder': 'Search all reports...',
    'reports.student.reports': 'Student Reports',
    'reports.financial.reports': 'Financial Reports',
    'reports.municipality.reports': 'Municipality Reports',
    'reports.statistics.reports': 'Statistics Reports',
    'reports.most.popular': 'Most popular:',
    'reports.show.all': 'Show all',
    'reports.recent.reports': 'Recent Reports',
    'reports.recent.scheduled': 'Recently generated and scheduled reports',
    'reports.saved.reports': 'Saved Reports',
    'reports.custom.templates': 'Custom and saved report templates',
    'reports.schedule': 'Schedule',
    'reports.download': 'Download',
    'reports.edit': 'Edit',
    'reports.generate': 'Generate',
    'reports.generated.by': 'Generated by:',
    'reports.last.run': 'Last run:',
    'reports.daily': 'Daily',
    'reports.weekly': 'Weekly',
    'reports.monthly': 'Monthly',
    'reports.quarterly': 'Quarterly',
    'reports.yearly': 'Yearly',
    'reports.termly': 'Termly',

    // Contribution Reports
    'contributions.title': 'Contribution Reports',
    'contributions.subtitle': 'Analysis of intercommunal compensations between municipalities',
    'contributions.historical.reports': 'Historical Reports',
    'contributions.export.data': 'Export Data',
    'contributions.filter.data': 'Filter Contribution Data',
    'contributions.period': 'Period',
    'contributions.select.period': 'Select period',
    'contributions.municipality': 'Municipality',
    'contributions.select.municipality': 'Select municipality',
    'contributions.all.municipalities': 'All municipalities',
    'contributions.program': 'Program',
    'contributions.select.program': 'Select program',
    'contributions.all.programs': 'All programs',
    'contributions.flow.type': 'Flow Type',
    'contributions.select.flow.type': 'Select flow type',
    'contributions.all.flows': 'All flows',
    'contributions.sent.payments': 'Sent payments',
    'contributions.received.payments': 'Received payments',
    'contributions.positive.net': 'Positive net status',
    'contributions.negative.net': 'Negative net status',
    'contributions.apply.filter': 'Apply filter',
    'contributions.total.contributions': 'Total Contributions',
    'contributions.from.last.month': 'from last month',
    'contributions.average.per.student': 'Average per Student',
    'contributions.monthly.average': 'Monthly average',
    'contributions.largest.recipient': 'Largest Recipient',
    'contributions.received': 'received',
    'contributions.largest.contributor': 'Largest Contributor',
    'contributions.sent': 'sent',
    'contributions.overview.per.municipality': 'Contribution Overview per Municipality',
    'contributions.detailed.overview': 'Detailed overview of municipal contribution flows',
    'contributions.students': 'students',
    'contributions.total.transaction.volume': 'Total transaction volume',
    'contributions.sent.contribution': 'Sent contribution',
    'contributions.received.contribution': 'Received contribution',
    'contributions.net.result': 'Net result:',
    'contributions.trends': 'Trends',
    'contributions.details': 'Details',
    'contributions.available.reports': 'Available Reports',
    'contributions.specialized.reports': 'Specialized contribution reports for different use cases',
    'contributions.municipal.summary': 'Municipal Summary',
    'contributions.municipal.summary.desc': 'Detailed summary of contribution flows between municipalities',
    'contributions.trend.analysis': 'Trend Analysis',
    'contributions.trend.analysis.desc': 'Analysis of contribution changes over time with trend forecasts',
    'contributions.economic.analysis': 'Economic Analysis',
    'contributions.economic.analysis.desc': 'Economic consequences of student movements between municipalities',
    'contributions.generate.report': 'Generate Report'
  },
  sv: {
    // Header
    'header.search.placeholder': 'Sök studenter, skolor, rapporter...',
    'header.breadcrumb.dashboard': 'Dashboard',
    'header.breadcrumb.students': 'Studenthantering > Studentregister',
    'header.breadcrumb.students.placements': 'Studenthantering > Placeringar & Överföringar',
    'header.breadcrumb.students.conflicts': 'Studenthantering > Konfliktlösning',
    'header.breadcrumb.students.bulk': 'Studenthantering > Massoperationer',
    'header.breadcrumb.financial': 'Ekonomihantering > IKE-beräkningar',
    'header.breadcrumb.financial.pricelists': 'Ekonomihantering > Prislistor',
    'header.breadcrumb.reports': 'Rapporter & Analys > Standardrapporter',
    'header.breadcrumb.reports.contributions': 'Rapporter & Analys > Bidragsrapporter',
    'header.breadcrumb.reports.statistics': 'Rapporter & Analys > Statistik',
    'header.breadcrumb.reports.follow-up': 'Rapporter & Analys > Uppföljningsrapporter',
    'header.breadcrumb.integration': 'Integration & Import',
    'header.breadcrumb.settings': 'Inställningar',
    
    // Dashboard
    'dashboard.welcome': 'Välkommen till IKE 2.0',
    'dashboard.date': 'Skåne Regional Platform',
    'dashboard.export': 'Exportera Data',
    'dashboard.generate': 'Generera Rapport',
    'dashboard.total.students': 'Totala Studenter',
    'dashboard.active.calculations': 'Aktiva Beräkningar',
    'dashboard.pending.conflicts': 'Väntande Konflikter',
    'dashboard.monthly.amount': 'Månadsbelopp',
    'dashboard.from.last.month': 'från förra månaden',
    'dashboard.ongoing.processing': 'Pågående processning',
    'dashboard.requires.attention': 'Kräver uppmärksamhet',
    'dashboard.for.november': 'SEK för november 2024',
    'dashboard.calculation.status': 'Aktuell Beräkningsstatus',
    'dashboard.monthly.calculation': 'Månatlig IKE-beräkning för november 2024',
    'dashboard.data.validation': 'Datavalidering',
    'dashboard.preliminary.calculation': 'Preliminär beräkning',
    'dashboard.final.calculation': 'Slutlig beräkning',
    'dashboard.completed': 'Klar',
    'dashboard.ongoing': 'Pågående',
    'dashboard.pending': 'Väntande',
    'dashboard.next.run': 'Nästa körning:',
    'dashboard.quick.actions': 'Snabbåtgärder',
    'dashboard.common.tasks': 'Vanliga uppgifter och funktioner',
    'dashboard.new.student': 'Ny Student',
    'dashboard.new.calculation': 'Ny Beräkning',
    'dashboard.resolve.conflicts': 'Lös Konflikter',
    'dashboard.recent.activity': 'Senaste Aktivitet',
    'dashboard.system.events': 'Översikt över systemhändelser och användaraktivitet',
    'dashboard.student.registered': 'Ny student registrerad',
    'dashboard.conflict.resolved': 'Konflikt löst',
    'dashboard.calculation.started': 'Beräkning startad',
    'dashboard.data.imported': 'Data importerad',
    'dashboard.done': 'Klar',
    'dashboard.resolved': 'Löst',
    
    // Students
    'students.title': 'Studentregister',
    'students.subtitle': 'Hantera studentregistrering och placeringar',
    'students.export': 'Exportera',
    'students.new.student': 'Ny Student',
    'students.total.students': 'Totala Studenter',
    'students.intercommunal': 'Interkommunala',
    'students.pending.transfers': 'Väntande Överföringar',
    'students.new.this.month': 'Nya denna månad',
    'students.search.filter': 'Sök och Filtrera',
    'students.search.placeholder': 'Sök efter namn eller personnummer...',
    'students.all.statuses': 'Alla statusar',
    'students.all.municipalities': 'Alla kommuner',
    'students.active': 'Aktiv',
    'students.conflict': 'Konflikt',
    'students.pending': 'Väntande',
    'students.unknown': 'Okänd',
    'students.student.list': 'Studenter',
    'students.detailed.list': 'Detaljerad lista över alla registrerade studenter',
    'students.name': 'Namn',
    'students.personal.number': 'Personnummer',
    'students.municipality': 'Kommun',
    'students.school': 'Skola',
    'students.program': 'Program',
    'students.class': 'Klass',
    'students.status': 'Status',
    'students.amount': 'Belopp (SEK)',
    'students.actions': 'Åtgärder',
    'students.view.details': 'Visa detaljer',
    'students.edit': 'Redigera',
    'students.transfer': 'Överför',

    // Student Placements
    'placements.title': 'Placeringar & Överföringar',
    'placements.subtitle': 'Hantera studentöverföringar mellan kommuner och skolor',
    'placements.new.transfer': 'Ny Överföring',
    'placements.pending.transfers': 'Väntande Överföringar',
    'placements.requires.approval': 'Kräver godkännande',
    'placements.approved.this.month': 'Godkända denna månad',
    'placements.from.last.month': 'från förra månaden',
    'placements.completed.transfers': 'Genomförda överföringar',
    'placements.since.term.start': 'Sedan terminsstart',
    'placements.current.requests': 'Aktuella Överföringsförfrågningar',
    'placements.recent.transfers': 'Pågående och nyligen genomförda studentöverföringar',
    'placements.from': 'Från:',
    'placements.to': 'Till:',
    'placements.program': 'Program:',
    'placements.reason': 'Anledning:',
    'placements.pending': 'Väntande',
    'placements.approved': 'Godkänd',
    'placements.completed': 'Genomförd',
    'placements.unknown': 'Okänd',
    'placements.approve': 'Godkänn',
    'placements.reject': 'Avslå',
    'placements.execute': 'Genomför',
    'placements.view.details': 'Visa detaljer',
    'placements.transfer.process': 'Överföringsprocess',
    'placements.process.description': 'Standardprocess för studentöverföringar mellan kommuner',
    'placements.step.application': 'Ansökan inkommen',
    'placements.step.application.desc': 'Student eller vårdnadshavare lämnar in ansökan',
    'placements.step.review': 'Granskning',
    'placements.step.review.desc': 'Både avgående och mottagande skola granskar ansökan',
    'placements.step.approval': 'Godkännande',
    'placements.step.approval.desc': 'Beslut fattas av ansvarig administrator',
    'placements.step.execution': 'Genomförande',
    'placements.step.execution.desc': 'Systemet uppdaterar studentregistret och beräknar nya bidrag',

    // Student Conflicts
    'conflicts.title': 'Konfliktlösning',
    'conflicts.subtitle': 'Identifiera och lösa konflikter i studentregistret',
    'conflicts.run.analysis': 'Kör Konfliktanalys',
    'conflicts.active.conflicts': 'Aktiva Konflikter',
    'conflicts.requires.attention': 'Kräver uppmärksamhet',
    'conflicts.under.investigation': 'Under Utredning',
    'conflicts.ongoing.process': 'Pågående process',
    'conflicts.resolved.this.month': 'Lösta denna månad',
    'conflicts.resolution.rate': '94% lösningsgrad',
    'conflicts.average.resolution.time': 'Genomsnittlig Lösningstid',
    'conflicts.days': 'dagar',
    'conflicts.active.conflicts.list': 'Aktiva Konflikter',
    'conflicts.requires.immediate.attention': 'Konflikter som kräver omedelbar uppmärksamhet och åtgärd',
    'conflicts.detected': 'Upptäckt:',
    'conflicts.responsible': 'Ansvarig:',
    'conflicts.school': 'Skola',
    'conflicts.choose.placement': 'Välj Placering',
    'conflicts.edit': 'Redigera',
    'conflicts.mark.resolved': 'Markera Löst',
    'conflicts.comments': 'Kommentarer',
    'conflicts.resolution.process': 'Konfliktlösningsprocess',
    'conflicts.standard.process': 'Standardprocess för att lösa konflikter i studentregistret',
    'conflicts.step.automatic.detection': 'Automatisk Upptäckt',
    'conflicts.step.automatic.detection.desc': 'Systemet identifierar potentiella konflikter vid dataregistrering',
    'conflicts.step.prioritization': 'Prioritering',
    'conflicts.step.prioritization.desc': 'Konflikter prioriteras baserat på typ och påverkan',
    'conflicts.step.investigation': 'Utredning',
    'conflicts.step.investigation.desc': 'Ansvarig administrator kontaktar berörda skolor',
    'conflicts.step.resolution': 'Lösning',
    'conflicts.step.resolution.desc': 'Korrekt placering bestäms och systemet uppdateras',
    'conflicts.double.registration': 'Dubbelregistrering',
    'conflicts.wrong.municipality': 'Felaktig kommun',
    'conflicts.date.conflict': 'Datum konflikt',
    'conflicts.pending': 'Väntande',
    'conflicts.investigating': 'Utreds',
    'conflicts.resolved': 'Löst',
    'conflicts.unknown': 'Okänd',
    'conflicts.priority.high': 'Hög',
    'conflicts.priority.medium': 'Medium',
    'conflicts.priority.low': 'Låg',

    // Bulk Operations
    'bulk.title': 'Massoperationer',
    'bulk.subtitle': 'Hantera stora mängder studentdata effektivt',
    'bulk.templates': 'Mallar',
    'bulk.new.operation': 'Ny Operation',
    'bulk.import.student.data': 'Importera Studentdata',
    'bulk.import.description': 'Importera data från SS12000 eller Excel-filer',
    'bulk.start.import': 'Starta Import',
    'bulk.year.advancement': 'Årskursavancemang',
    'bulk.advancement.description': 'Avancera studenter till nästa årskurs',
    'bulk.start.advancement': 'Starta Avancemang',
    'bulk.export.data': 'Exportera Data',
    'bulk.export.description': 'Exportera studentdata för rapporter eller backup',
    'bulk.start.export': 'Starta Export',
    'bulk.recent.operations': 'Pågående och Senaste Operationer',
    'bulk.operations.description': 'Status för massoperationer och dataprocessning',
    'bulk.started.by': 'Startad av:',
    'bulk.progress': 'Framsteg',
    'bulk.total': 'Totalt:',
    'bulk.processed': 'Bearbetat:',
    'bulk.successful': 'Framgångsrikt:',
    'bulk.failed': 'Misslyckade:',
    'bulk.start': 'Start:',
    'bulk.end': 'Slut:',
    'bulk.not.started': 'Ej startad',
    'bulk.cancel': 'Avbryt',
    'bulk.show.errors': 'Visa Fel',
    'bulk.details': 'Detaljer',
    'bulk.completed': 'Klar',
    'bulk.running': 'Pågående',
    'bulk.pending': 'Väntande',
    'bulk.failed.status': 'Misslyckad',
    'bulk.unknown': 'Okänd',
    'bulk.import.guidelines': 'Importriktlinjer',
    'bulk.guidelines.description': 'Viktiga riktlinjer för dataimport och massoperationer',
    'bulk.ss12000.standard': 'SS12000 Standard',
    'bulk.ss12000.description': 'Använd SS12000-formatet för att säkerställa kompatibilitet och datakvalitet',
    'bulk.validation.before.import': 'Validering före Import',
    'bulk.validation.description': 'Verifiera alltid data i testmiljö innan import till produktionssystemet',
    'bulk.backup.before.operations': 'Backup före Massoperationer',
    'bulk.backup.description': 'Säkerställ att fullständig backup finns innan stora ändringar genomförs',
    'bulk.communication': 'Kommunikation',
    'bulk.communication.description': 'Informera berörda parter om planerade massoperationer i god tid',

    // Financial
    'financial.title': 'IKE-beräkningar',
    'financial.subtitle': 'Hantera månatliga beräkningar för interkommunal ersättning',
    'financial.export.results': 'Exportera Resultat',
    'financial.new.calculation': 'Ny Beräkning',
    'financial.total.monthly.cost': 'Total Månadskostnad',
    'financial.from.last.month': 'från förra månaden',
    'financial.average.per.student': 'Genomsnitt per Student',
    'financial.monthly.average': 'Månadsgenomsnitt',
    'financial.active.students': 'Aktiva Studenter',
    'financial.included.in.calculation': 'Inkluderade i beräkning',
    'financial.next.calculation': 'Nästa Beräkning',
    'financial.scheduled.run': 'Schemalagd körning',
    'financial.current.calculation.status': 'Aktuell Beräkningsstatus',
    'financial.detailed.status': 'Detaljerad status för pågående månatlig beräkning',
    'financial.data.validation': 'Datavalidering',
    'financial.price.calculation': 'Prisberäkning',
    'financial.export.distribution': 'Export & Distribution',
    'financial.completed': 'Klar',
    'financial.ongoing': 'Pågående',
    'financial.pending': 'Väntande',
    'financial.validated.posts': 'Validerat {count} studentposter',
    'financial.processed.students': 'Bearbetat {current} av {total} studenter',
    'financial.waiting.completion': 'Väntar på beräkningskomplettering',
    'financial.started': 'Startad:',
    'financial.estimated.completion': 'Beräknad färdig:',
    'financial.show.details': 'Visa Detaljer',
    'financial.calculation.history': 'Beräkningshistorik',
    'financial.previous.calculations': 'Översikt över tidigare månatliga beräkningar',
    'financial.completed.short': 'Färdig:',
    'financial.total.amount': 'Totalt belopp:',
    'financial.number.of.students': 'Antal studenter:',
    'financial.average.per.student.short': 'Genomsnitt/student:',
    'financial.details': 'Detaljer',
    'financial.export': 'Export',
    'financial.municipality.breakdown': 'Kommunfördelning',
    'financial.cost.distribution': 'Kostnadsfördeling per kommun för aktuell månad',
    'financial.students': 'studenter',
    'financial.sek.per.student': 'SEK/student',
    'financial.failed': 'Misslyckad',
    'financial.unknown': 'Okänd',

    // Price Lists
    'pricelists.title': 'Prislistor',
    'pricelists.subtitle': 'Hantera priser för program och specialiseringar',
    'pricelists.price.history': 'Prishistorik',
    'pricelists.new.pricelist': 'Ny Prislista',
    'pricelists.active.pricelists': 'Aktiva Prislistor',
    'pricelists.over.municipalities': 'Över 33 kommuner',
    'pricelists.average.price': 'Genomsnittspris',
    'pricelists.sek.per.student.year': 'SEK per student/år',
    'pricelists.updates.this.year': 'Uppdateringar i år',
    'pricelists.price.changes.2024': 'Prisändringar 2024',
    'pricelists.price.increase': 'Prisökning',
    'pricelists.compared.to.2023': 'Jämfört med 2023',
    'pricelists.pricelists.per.municipality': 'Prislistor per Kommun',
    'pricelists.overview.active.planned': 'Översikt över aktiva och planerade prislistor',
    'pricelists.search.pricelists': 'Sök prislistor...',
    'pricelists.municipality': 'Kommun',
    'pricelists.type': 'Typ',
    'pricelists.valid.from': 'Giltig från',
    'pricelists.valid.to': 'Giltig till',
    'pricelists.programs': 'Program',
    'pricelists.average.price.short': 'Genomsnittspris',
    'pricelists.status': 'Status',
    'pricelists.actions': 'Åtgärder',
    'pricelists.active': 'Aktiv',
    'pricelists.draft': 'Utkast',
    'pricelists.expired': 'Utgången',
    'pricelists.unknown': 'Okänd',
    'pricelists.program.prices.malmo': 'Programpriser - Malmö Kommun',
    'pricelists.detailed.prices': 'Detaljerade priser för olika program och specialiseringar',
    'pricelists.program.code': 'Programkod',
    'pricelists.program.name': 'Programnamn',
    'pricelists.specialization': 'Specialisering',
    'pricelists.normal.price': 'Normalpris',
    'pricelists.internal.price': 'Internt pris',
    'pricelists.price.trends': 'Pristrender',
    'pricelists.development.average.prices': 'Utveckling av genomsnittspriser över tid',
    'pricelists.interactive.trend.chart': 'Interaktivt trenddiagram skulle visas här',
    'pricelists.visualization.price.changes': '(Visualisering av prisförändringar över tid)',
    'pricelists.from.previous.year': 'från {year}',

    // Reports
    'reports.title': 'Standardrapporter',
    'reports.subtitle': 'Generera och hantera vanliga systemrapporter',
    'reports.new.report': 'Ny Rapport',
    'reports.search.placeholder': 'Sök i alla rapporter...',
    'reports.student.reports': 'Studentrapporter',
    'reports.financial.reports': 'Ekonomirapporter',
    'reports.municipality.reports': 'Kommunrapporter',
    'reports.statistics.reports': 'Statistikrapporter',
    'reports.most.popular': 'Mest populär:',
    'reports.show.all': 'Visa alla',
    'reports.recent.reports': 'Senaste Rapporter',
    'reports.recent.scheduled': 'Nyligen genererade och schemalagda rapporter',
    'reports.saved.reports': 'Sparade Rapporter',
    'reports.custom.templates': 'Anpassade och sparade rapportmallar',
    'reports.schedule': 'Schema',
    'reports.download': 'Ladda ner',
    'reports.edit': 'Redigera',
    'reports.generate': 'Generera',
    'reports.generated.by': 'Genererad av:',
    'reports.last.run': 'Senast körd:',
    'reports.daily': 'Dagligen',
    'reports.weekly': 'Veckovis',
    'reports.monthly': 'Månadsvis',
    'reports.quarterly': 'Kvartalsvis',
    'reports.yearly': 'Årligen',
    'reports.termly': 'Terminsvis',

    // Contribution Reports
    'contributions.title': 'Bidragsrapporter',
    'contributions.subtitle': 'Analys av interkommunala ersättningar mellan kommuner',
    'contributions.historical.reports': 'Historiska rapporter',
    'contributions.export.data': 'Exportera data',
    'contributions.filter.data': 'Filtrera bidragsdata',
    'contributions.period': 'Period',
    'contributions.select.period': 'Välj period',
    'contributions.municipality': 'Kommun',
    'contributions.select.municipality': 'Välj kommun',
    'contributions.all.municipalities': 'Alla kommuner',
    'contributions.program': 'Program',
    'contributions.select.program': 'Välj program',
    'contributions.all.programs': 'Alla program',
    'contributions.flow.type': 'Flödestyp',
    'contributions.select.flow.type': 'Välj flödestyp',
    'contributions.all.flows': 'Alla flöden',
    'contributions.sent.payments': 'Skickade betalningar',
    'contributions.received.payments': 'Mottagna betalningar',
    'contributions.positive.net': 'Positiv nettostatus',
    'contributions.negative.net': 'Negativ nettostatus',
    'contributions.apply.filter': 'Tillämpa filter',
    'contributions.total.contributions': 'Total bidrag',
    'contributions.from.last.month': 'från förra månaden',
    'contributions.average.per.student': 'Genomsnitt per student',
    'contributions.monthly.average': 'Månadsgenomsnitt',
    'contributions.largest.recipient': 'Största bidragsmottagare',
    'contributions.received': 'mottaget',
    'contributions.largest.contributor': 'Största bidragsgivare',
    'contributions.sent': 'skickat',
    'contributions.overview.per.municipality': 'Bidragsöversikt per Kommun',
    'contributions.detailed.overview': 'Detaljerad översikt över kommunala bidragsflöden',
    'contributions.students': 'studenter',
    'contributions.total.transaction.volume': 'Total transaktionsvolym',
    'contributions.sent.contribution': 'Skickat bidrag',
    'contributions.received.contribution': 'Mottaget bidrag',
    'contributions.net.result': 'Nettoresultat:',
    'contributions.trends': 'Trender',
    'contributions.details': 'Detaljer',
    'contributions.available.reports': 'Tillgängliga Rapporter',
    'contributions.specialized.reports': 'Specialiserade bidragsrapporter för olika användningsfall',
    'contributions.municipal.summary': 'Kommunal Sammanställning',
    'contributions.municipal.summary.desc': 'Detaljerad sammanställning av bidragsflöden mellan kommuner',
    'contributions.trend.analysis': 'Trendanalys',
    'contributions.trend.analysis.desc': 'Analys av bidragsförändringar över tid med trendprognoser',
    'contributions.economic.analysis': 'Ekonomisk Analys',
    'contributions.economic.analysis.desc': 'Ekonomiska konsekvenser av studentrörelser mellan kommuner',
    'contributions.generate.report': 'Generera rapport'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'sv' : 'en');
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
